/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Asus
 */
public class MULTI_SEARCH_DESIGN extends javax.swing.JPanel {

    /**
     * Creates new form MULTI_SEARCH_DESIGN
     */
    public MULTI_SEARCH_DESIGN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        photo = new javax.swing.JLabel();
        release_date = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        overview = new javax.swing.JButton();

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setLayout(null);

        photo.setText("jLabel1");
        add(photo);
        photo.setBounds(10, 10, 150, 180);

        release_date.setText("jLabel2");
        add(release_date);
        release_date.setBounds(190, 80, 250, 40);

        name.setText("jLabel2");
        add(name);
        name.setBounds(190, 20, 250, 40);

        overview.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        overview.setText("OVERVIEW");
        add(overview);
        overview.setBounds(190, 140, 180, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    public javax.swing.JLabel name;
    public javax.swing.JButton overview;
    public javax.swing.JLabel photo;
    public javax.swing.JLabel release_date;
    // End of variables declaration//GEN-END:variables
}
